# Dockerfile for abc.docker-registry.gewis.nl/eou/texlive:22.04, should only be rebuilt if absolutely necessary.
FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y texlive-full git curl && \
    apt-get clean && rm -rf /var/lib/apt/lists/*