services:
  texlive-packages:
    image: texlive/texlive:latest
    volumes:
      - texlive-pkgs:/usr/share/texlive
    command: [ "sleep", "infinity" ]

  templates:
    image: abc.docker-registry.gewis.nl/eou/templates:latest
    volumes:
      - templates-data:/data/templates
    command: ["sleep", "infinity"]

  pdf-compiler:
    image: abc.docker-registry.gewis.nl/eou/pdf-compiler:latest
    ports:
      - "8080:80"
    environment:
      - BASE_PATH=/api/v1
      - TEMPLATE_DIR=/templates/BAC
      - PATH=/usr/bin:$PATH
    depends_on:
      - texlive-packages
      - templates
    volumes:
      - texlive-pkgs:/usr/share/texlive:ro
      - templates-data:/templates:ro

volumes:
  texlive-pkgs:
  templates-data:
