// This file is auto-generated by @hey-api/openapi-ts

export type MainCompileRequest = {
  tex?: string;
};

export type PostCompileData = {
  /**
   * LaTeX template
   */
  body: MainCompileRequest;
  path?: never;
  query?: never;
  url: '/compile';
};

export type PostCompileErrors = {
  /**
   * Invalid request
   */
  400: {
    [key: string]: string;
  };
  /**
   * Compilation error
   */
  500: {
    [key: string]: string;
  };
};

export type PostCompileError = PostCompileErrors[keyof PostCompileErrors];

export type PostCompileResponses = {
  /**
   * PDF file
   */
  200: unknown;
};

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};
