// This file is auto-generated by @hey-api/openapi-ts

export type MainCompileRequest = {
  tex?: string;
};

export type MainErrorResponse = {
  error?: string;
};

export type PostCompileData = {
  /**
   * LaTeX template
   */
  body: MainCompileRequest;
  path?: never;
  query?: never;
  url: '/compile';
};

export type PostCompileErrors = {
  /**
   * Invalid request
   */
  400: MainErrorResponse;
  /**
   * Compilation error
   */
  500: MainErrorResponse;
};

export type PostCompileError = PostCompileErrors[keyof PostCompileErrors];

export type PostCompileResponses = {
  /**
   * PDF file
   */
  200: string;
};

export type PostCompileResponse = PostCompileResponses[keyof PostCompileResponses];

export type GetHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/health';
};

export type GetHealthResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type ClientOptions = {
  baseUrl: 'http://localhost:8080/api/v1' | (string & {});
};
