// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "components": {"schemas":{"main.CompileRequest":{"properties":{"tex":{"example":"\\documentclass{article}\n\\begin{document}\nHello, world!\n\\end{document}","type":"string"}},"type":"object"},"main.ErrorResponse":{"properties":{"error":{"example":"Invalid request, must provide LaTeX template","type":"string"}},"type":"object"}}},
    "info": {"description":"{{escape .Description}}","title":"{{.Title}}","version":"{{.Version}}"},
    "externalDocs": {"description":"","url":""},
    "paths": {"/compile":{"post":{"description":"Compiles a LaTeX template and returns a PDF","requestBody":{"content":{"application/json":{"schema":{"$ref":"#/components/schemas/main.CompileRequest"}}},"description":"LaTeX template","required":true},"responses":{"200":{"content":{"application/json":{"schema":{"type":"string"}},"application/pdf":{"schema":{"format":"binary","type":"string"}}},"description":"PDF file"},"400":{"content":{"application/json":{"schema":{"$ref":"#/components/schemas/main.ErrorResponse"}}},"description":"Invalid request"},"500":{"content":{"application/json":{"schema":{"$ref":"#/components/schemas/main.ErrorResponse"}}},"description":"Compilation error"}},"summary":"Compile LaTeX template","tags":["Compile"]}},"/health":{"get":{"description":"Returns 200 OK","responses":{"200":{"description":"OK"}},"summary":"Health check","tags":["Health"]}}},
    "openapi": "3.1.0",
    "servers": [
        {"url":"http://localhost:8080/api/v1"}
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Title:            "PDF Compiler",
	Description:      "Compiles a LaTeX template and returns a PDF",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
