name: Docker Build

on:
  push:
    branches:
      - main
      -
permissions:
  contents: read

jobs:
  build:
    uses: GEWIS/actions/.github/workflows/docker-build.yml@v1.8.1
    with:
      projects: '["."]'
      docker-registry: 'abc.docker-registry.gewis.nl'
      prepare-command: |
        git clone --depth=1 https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/GEWIS/latex-templates.git templates
    secrets:
      REGISTRY_USERNAME: ${{ secrets.SVC_GH_ABCEOU_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.SVC_GH_ABCEOU_PWD }}