name: Lint and build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-lint:
    uses: GEWIS/actions/.github/workflows/lint-and-build-go.yml@v1
    with:
      go-version: "^1.24.0"
      lint: true
      format: true
      build: true
      test: true
