name: Lint and build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-lint-server:
    uses: GEWIS/actions/.github/workflows/lint-and-build-go.yml@v1
    with:
      go-version: "^1.24.0"
      lint: true
      format: true
      build: true
      test: true

  build-and-lint-client:
    uses: GEWIS/actions/.github/workflows/lint-and-build-yarn.yml@v1
    with:
      node-version: "^22.0.0"
      lint: true
      format: true
      build: true
      test: true
      working-directory: './client'
      prepare-command: "docker build . -t test-image && docker compose -f docker-compose.test.yaml up -d"
      cleanup-command: 'docker compose -f docker-compose.test.yaml down'

